name: Eucleia Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.14.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true
    - name: Build
      run: bazel build //... --config=release
    - name: Functional Tests
      run: bazel test test/functional:functional --config=release
    - name: Benchmarking Tests 
      run: bazel test test/benchmark:benchmark --config=release --test_output=all
